# Generated by Django 4.2.2 on 2023-06-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_category_card_correct_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='correct_answers',
            new_name='knownAnswerCount',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='incorrect_answers',
            new_name='unknownAnswerCount',
        ),
    ]
