# Generated by Django 4.2.2 on 2023-06-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='box',
        ),
    ]
