# Generated by Django 4.2.2 on 2023-06-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
